
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action OpenFileAction;
	
	private global::Gtk.Action AddFileAction;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView TextEditor;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Entry entry2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow4;
	
	private global::Gtk.TreeView LexTree;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Entry entry3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView SymbolTable;
	
	private global::Gtk.Button ExecuteBtn;
	
	private global::Gtk.Label ConsoleLabel;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView Console;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.OpenFileAction = new global::Gtk.Action ("OpenFileAction", global::Mono.Unix.Catalog.GetString ("Open File"), null, null);
		this.OpenFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("CODE");
		w1.Add (this.OpenFileAction, null);
		this.AddFileAction = new global::Gtk.Action ("AddFileAction", global::Mono.Unix.Catalog.GetString ("Add File"), null, null);
		this.AddFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add File");
		w1.Add (this.AddFileAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'OpenFileAction\' action=\'OpenFileAction\'>" +
		"<menuitem name=\'AddFileAction\' action=\'AddFileAction\'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextEditor = new global::Gtk.TextView ();
		this.TextEditor.WidthRequest = 30;
		this.TextEditor.CanFocus = true;
		this.TextEditor.Name = "TextEditor";
		this.GtkScrolledWindow.Add (this.TextEditor);
		this.hbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString ("LEXEMES");
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.vbox3.Add (this.entry2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.LexTree = new global::Gtk.TreeView ();
		this.LexTree.CanFocus = true;
		this.LexTree.Name = "LexTree";
		this.GtkScrolledWindow4.Add (this.LexTree);
		this.vbox3.Add (this.GtkScrolledWindow4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow4]));
		w7.Position = 1;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w8.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.WidthRequest = 10;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = global::Mono.Unix.Catalog.GetString ("SYMBOL TABLE");
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.vbox4.Add (this.entry3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.SymbolTable = new global::Gtk.TreeView ();
		this.SymbolTable.CanFocus = true;
		this.SymbolTable.Name = "SymbolTable";
		this.GtkScrolledWindow2.Add (this.SymbolTable);
		this.vbox4.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow2]));
		w11.Position = 1;
		this.hbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
		w12.Position = 2;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w13.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.ExecuteBtn = new global::Gtk.Button ();
		this.ExecuteBtn.CanFocus = true;
		this.ExecuteBtn.Name = "ExecuteBtn";
		this.ExecuteBtn.UseUnderline = true;
		this.ExecuteBtn.Label = global::Mono.Unix.Catalog.GetString ("EXECUTE");
		this.vbox2.Add (this.ExecuteBtn);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ExecuteBtn]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.ConsoleLabel = new global::Gtk.Label ();
		this.ConsoleLabel.Name = "ConsoleLabel";
		this.ConsoleLabel.Xpad = 10;
		this.ConsoleLabel.Xalign = 0F;
		this.ConsoleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Console");
		this.vbox2.Add (this.ConsoleLabel);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ConsoleLabel]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.Console = new global::Gtk.TextView ();
		this.Console.CanFocus = true;
		this.Console.Name = "Console";
		this.Console.Editable = false;
		this.GtkScrolledWindow1.Add (this.Console);
		this.hbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow1]));
		w17.Position = 0;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w18.Position = 4;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1077;
		this.DefaultHeight = 733;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AddFileAction.Activated += new global::System.EventHandler (this.OnAddFileActionActivated);
		this.ExecuteBtn.Clicked += new global::System.EventHandler (this.OnExecuteBtnClicked);
	}
}
