HAI BTW I HOPE YOU LIKE MY FIBONACCI SEQUENCE
I HAS A TARGET ITZ 25
I HAS A COUNTER ITZ 2
I HAS A NUMBR1 ITZ 0
I HAS A NUMBR2 ITZ 1
VISIBLE SMOOSH "0 : " NUMBR1 MKAY
VISIBLE SMOOSH "1 : " NUMBR2 MKAY
IM IN YR LOOP UPPIN YR COUNTER TIL BOTH SAEM COUNTER AN TARGET
  NUMBR R SUM OF NUMBR1 AN NUMBR2
  NUMBR1 R NUMBR2
  NUMBR2 R NUMBR
  X R SMOOSH COUNTER " : " MKAY
  VISIBLE SMOOSH X AN NUMBR MKAY
IM OUTTA YR LOOP
KTHXBYE