HAI BTW this is an example of using if-else
I HAS A ANIMAL
GIMMEH ANIMAL
BOTH SAEM ANIMAL AN "CAT" 
O RLY?
  YA RLY
    VISIBLE "J00 HAV A CAT"
  MEBBE BOTH SAEM ANIMAL AN 12
    VISIBLE "NOM NOM NOM. I EATED IT."
  NO WAI
    VISIBLE "J00 SUX"
OIC'
KTHXBYE