HAI
I HAS A COLOR ITZ "GREEN"
IT R COLOR
COLOR, WTF?
  OMG "R"
    VISIBLE "RED FISH"
    GTFO
  OMG "Y"
    VISIBLE "YELLOW FISH"
  OMG "GREEN"
  OMG "B"
    VISIBLE "FISH HAS A FLAVOR"
  OMGWTF
    VISIBLE "FISH IS TRANSPARENT"
OIC
KTHXBYE