HAI
BTW Declaration
I  HAS A NUMBER
I HAS     A number ITZ 1
I HAS A STR ITZ "Hello:) World!"

BTW Input Output
GIMMEH NUMBER
VISIBLE number STR

BTW Casting
NUMBER IS    NOW A NUMBAR

BTW Operations
NUMBER R SUM OF NUMBER AN 5
BOTH OF WIN AN FAIL
BOTH SAEM NUMBER AN number

BTW Concatenation
VISIBLE SMOOSH "Hi!" AN STR MKAY

BTW If-else
BOTH SAEM 1 AN "CAT"
O RLY?
  YA RLY
    VISIBLE "YU HAV A CAT"
  MEBBE BOTH SAEM ANIMAL AN "MAUS"
    VISIBLE "YU HAV A MAUS"
  NO WAI
    VISIBLE "YU DONT NO"
OIC
  
BTW Case
COLOR, WTF?
  OMG "R"
    VISIBLE "RED FISH"
    GTFO
  OMG "G"
  OMG "B"
    VISIBLE "FISH HAS A FLAVOR"
    GTFO
  OMGWTF
    VISIBLE "FISH IS TRANSPARENT"
OIC

BTW Loop
IM IN YR LOOP UPPIN YR N WILE DIFFRINT N AND SMALLR OF N AN 10
    VISIBLE N
    ANS R SUM OF ANS AN 1 
 IM OUTTA YR LOOP

KTHXBYE

BTW Function (Bonus)
HOW DUZ I ADD YR NUM1 AN YR NUM2
  SUM OF NUM1 AN NUM2
IF U SAY SO

HAI
BTW Loop
IM IN YR LOOP UPPIN YR N WILE DIFFRINT N AND BIGGR OF N AN 10
    VISIBLE N
    ANS R SUM OF ANS AN 1 
 IM OUTTA YR LOOP
 KTHXBYE
