HAI
	BTW Declaration
	I  HAS A NUMBER
	I HAS     A number ITZ 1
	I HAS A STR ITZ "Hello:) World!"

	BTW Input Output
	GIMMEH NUMBER
	VISIBLE number STR
	VISIBLE BOTH SAEM NUMBER AN number
	VISIBLE QUOSHUNT OF 10 AN 2

	BTW Casting
	NUMBER IS    NOW A NUMBAR

	BTW Operations
	NUMBER R SUM OF NUMBER AN 55
	BOTH OF WIN AN FAIL

	BTW Concatenation
	VISIBLE SMOOSH "Hi! " AN STR MKAY

	BTW If-else
	BOTH SAEM ANIMAL AN "CAT"
	O RLY?
		YA RLY
			VISIBLE "YU HAV A CAT"
		NO WAI
			VISIBLE "YU DONT NO"
	OIC
	OBTW
	BTW Case
	IT R "B"
	COLOR, WTF?
		OMG "R"
			VISIBLE "RED FISH"
			GTFO
		OMG "B"
			VISIBLE "FISH HAS A FLAVOR"
			GTFO
		OMGWTF
			VISIBLE "FISH IS TRANSPARENT"
	OIC
	TLDR

	BTW Loop (Bonus)
	IM IN YR LOOP UPPIN YR N WILE DIFFRINT N AND SMALLR OF N AN 10
		VISIBLE N
		ANS R SUM OF ANS AN 1
		BTW Case
		IT R "B"
		COLOR, WTF?
			OMG "R"
				VISIBLE "RED FISH"
				GTFO
			OMG "B"
				VISIBLE "FISH HAS A FLAVOR"
				GTFO
			OMGWTF
				VISIBLE "FISH IS TRANSPARENT"
		OIC
	IM OUTTA YR LOOP

KTHXBYE